<?php
$typeArr[1] = '新闻中心';
$typeArr[2] = '公司新闻';
$typeArr[3] = '行业咨询';
$typeArr[4] = '家居艺术';
$typeArr[5] = '活动资讯';
$typeArr[6] = '奥凡产品';
$typeArr[25] = '企业文化';
$typeArr[24] = '公司简介';
$typeArr[23] = '服务中心';
$typeArr[22] = '加盟澳凡';
$typeArr[21] = '营销网络';
$typeArr[12] = '关于奥凡';
$typeArr[27] = '发展历程';
$typeArr[26] = '资质荣誉';
$typeArr[18] = '系列一';
$typeArr[20] = '系列三';
$typeArr[19] = '系列二';
$typeArr[28] = '联系我们';
$typeArr[29] = '售后服务';
$typeArr[30] = '家具常识';
$typeArr[31] = '在线留言';
?>