<li class="content column-num2">
																	<div class="pic-module">
																		<div class="pic">
																			<a href="[field:litpic/]" title="海棠木系列" target="_self"> <img id="FrontProducts_list01-1384134850405_203" src="%E6%B7%B1%E5%9C%B3%E5%B8%82%E6%9C%A8%E5%8C%A0%E5%A4%A7%E5%B8%88%E5%AE%B6%E5%85%B7%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8_files/73c36d54-7144-48a9-9e66-414d95c306c9.jpg" onerror="this.src='/images/common/noimage.jpg'" alt="" title="海棠木系列"> </a>
																		</div>
																	</div>
																	<div class="pro-module">
																		<ul class="basic">
																			<li class="code">
																				<h1><span>产品名称：</span><strong> 海棠木系列</strong></h1>
																			</li>
																			<li class="detaillinks">
																				<a href="http://www.mujiang.com/products_detail/&amp;productId=203.html" title="海棠木系列" target="_self">详细内容</a>
																			</li>
																		</ul>
																		<p class="buttonP"></p>
																	</div>
																</li>