<?php
$z[0]=Array("arcurl","",142,157);
$z[1]=Array("title","",166,206);
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("litpic","",278,293);
$z[3]=Array("litpic","",318,333);
$z[4]=Array("title","",345,385);
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("title","",394,434);
$z[5][4]['function']="html2text(@me)";
$z[6]=Array("title","",674,714);
$z[6][4]['function']="html2text(@me)";
$z[7]=Array("arcurl","",830,845);
$z[8]=Array("title","",854,894);
$z[8][4]['function']="html2text(@me)";

?>