<li class="content column-num1">
															<div class="newstitle">
																<ul>
																	<li class="title">
																		<h3><a href="[field:arcurl/]" title="[field:title/]" target="_self"> [field:title/]...</a></h3>
																	</li>
																	<li class="date">
																		<span></span>2013-11-11
																	</li>
																</ul>
															</div>
														</li>
														<li class="clearBoth"></li>