<?php
$z[0]=Array("arclist","\r\n														<li class=\"content column-num1\">\r\n															<div class=\"newstitle\">\r\n																<ul>\r\n																	<li class=\"title\">\r\n																		<h3><a href=\"http://www.mujiang.com/news_detail/newsId=19.html\" title=\"2010年家居业最值得回味十大流行语\" target=\"_self\"> 2010年家居业最值...</a></h3>\r\n																	</li>\r\n																	<li class=\"date\">\r\n																		<span></span>2013-11-11\r\n																	</li>\r\n																</ul>\r\n															</div>\r\n														</li>\r\n														<li class=\"clearBoth\"></li>",0,624);
$z[0][4]['titlelen']="42";
$z[0][4]['row']="3";

?>