<?php
$z[0]=Array("litpic","",130,145);
$z[1]=Array("title","",154,194);
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("litpic","",266,281);
$z[3]=Array("litpic","",302,317);
$z[4]=Array("title","",325,365);
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("title","",374,414);
$z[5][4]['function']="html2text(@me)";
$z[6]=Array("title","",630,670);
$z[6][4]['function']="html2text(@me)";
$z[7]=Array("litpic","",774,789);
$z[8]=Array("title","",798,838);
$z[8][4]['function']="html2text(@me)";

?>