<?php
$z[0]=Array("arcurl","",142,157);
$z[1]=Array("title","",166,206);
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("litpic","",278,293);
$z[3]=Array("title","",356,396);
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("title","",405,445);
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("title","",685,725);
$z[5][4]['function']="html2text(@me)";
$z[6]=Array("litpic/"","",841,904);
$z[6][4]['title']="[field:title function='html2text(@me)'";

?>