<li class="content column-num2">
																	<div class="pic-module">
																		<div class="pic">
																			<a href="[field:arcurl/]" title="[field:title function='html2text(@me)'/]" target="_self"> <img id="FrontProducts_list01-1384134850405_269" src="[field:litpic/]" onerror="this.src=&#39;/images/common/noimage.jpg&#39;" alt="[field:title function='html2text(@me)'/]" title="[field:title function='html2text(@me)'/]"> </a>
																		</div>
																	</div>
																	<div class="pro-module">
																		<ul class="basic">
																			<li class="code">
																				<h1><span>产品名称：</span><strong> [field:title function='html2text(@me)'/]</strong></h1>
																			</li>
																			<li class="detaillinks">
																				<a href="http://www.mujiang.com/products_detail/&productId=269.html" title="[field:title function='html2text(@me)'/]" target="_self">详细内容</a>
																			</li>
																		</ul>
																		<p class="buttonP"></p>
																	</div>
																</li>
																
																<li class="clearBoth"></li>
																<li class="content column-num2">
																	<div class="pic-module">
																		<div class="pic">
																			<a href="http://www.mujiang.com/imageRepository/19de90fc-8a5d-4f32-8fc4-6e2b5389158f.jpg" title="间厅柜" target="_self"> <img id="FrontProducts_list01-1384134850405_265" src="{dede:global.cfg_cmsurl/}/images/list_image_files/816dd8fe-5416-45fa-9017-9818b878b3a6.jpg" onerror="this.src=&#39;/images/common/noimage.jpg&#39;" alt="" title="间厅柜"> </a>
																		</div>
																	</div>
																	<div class="pro-module">
																		<ul class="basic">
																			<li class="code">
																				<h1><span>产品名称：</span><strong> 间厅柜</strong></h1>
																			</li>
																			<li class="detaillinks">
																				<a href="http://www.mujiang.com/products_detail/&productId=265.html" title="间厅柜" target="_self">详细内容</a>
																			</li>
																		</ul>
																		<p class="buttonP"></p>
																	</div>
																</li>
																<li class="content column-num2">
																	<div class="pic-module">
																		<div class="pic">
																			<a href="http://www.mujiang.com/imageRepository/8fa26107-7db1-46a0-a807-cc439be8f0f4.jpg" title="圆餐桌/餐椅" target="_self"> <img id="FrontProducts_list01-1384134850405_264" src="{dede:global.cfg_cmsurl/}/images/list_image_files/82eb2a7f-3393-4a31-b5e8-3347f9f6da6b.jpg" onerror="this.src=&#39;/images/common/noimage.jpg&#39;" alt="" title="圆餐桌/餐椅"> </a>
																		</div>
																	</div>
																	<div class="pro-module">
																		<ul class="basic">
																			<li class="code">
																				<h1><span>产品名称：</span><strong> 圆餐桌/餐椅</strong></h1>
																			</li>
																			<li class="detaillinks">
																				<a href="http://www.mujiang.com/products_detail/&productId=264.html" title="圆餐桌/餐椅" target="_self">详细内容</a>
																			</li>
																		</ul>
																		<p class="buttonP"></p>
																	</div>
																</li>
																<li class="clearBoth"></li>