<li>
													<a href="{dede:field name='typeurl'/}">{dede:field name='typename'/}</a>
												</li>
												
												<li class="last"></li>
											</ul>
										</div>
										<ul id="summenu_FrontColumns_navigation01-1383536761574_2" class="ddsubmenustyle" style="z-index: 2000; visibility: hidden;">{dede:channel type='son' noself='yes'}
											<li>
												<a href="[field:typelink/]">[field:typename/]</a>
											</li>{/dede:channel}