<li>
													<a href="{dede:field name='typeurl'/}" rel="" title="{dede:field name='typename'/}"> {dede:field name='typename'/}</a>
												</li>
												</li>
												<li class="last"></li>
											</ul>
										</div>
										<ul id="" class="ddsubmenustyle" style="z-index: 2000; visibility: hidden;">{dede:channel type='son' noself='yes'}
											<li>
												<a href="[field:typelink/]"> [field:typename/]</a>
											</li>
										{/dede:channel}
										</ul>