<?php
$z[0]=Array("arcurl","",142,157);
$z[1]=Array("title","",166,206);
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("litpic","",278,293);
$z[3]=Array("litpic","",313,328);
$z[4]=Array("title","",335,375);
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("title","",384,424);
$z[5][4]['function']="html2text(@me)";
$z[6]=Array("title","",664,704);
$z[6][4]['function']="html2text(@me)";
$z[7]=Array("arcurl","",820,835);
$z[8]=Array("title","",844,884);
$z[8][4]['function']="html2text(@me)";

?>