<li class="title">
																<h3><a href="[field:arcurl/]" title="[field:title/]" target="_self"> [field:title/]</a></h3>
															</li>
															
															<li class="date">
																<span></span>[field:pubdate function="MyDate('m-d',@me)"/]
															</li>
															
														</ul>
													</div>
												</li>
												<li class="clearBoth"></li>
												<li class="showLine"></li>