<?php
$z[0]=Array("arclist","\r\n														<li class=\"content column-num1\">\r\n															<div class=\"newstitle\">\r\n																<ul>\r\n																	<li class=\"title\">\r\n																		<h3><a href=\"http://www.mujiang.com/news_detail/newsId=13.html\" title=\"[field:title/]-深圳展会消息\" target=\"_self\"> [field:title/]...</a></h3>\r\n																	</li>\r\n																	<li class=\"date\">\r\n																		<span></span>[field:pubdate function=\"GetDateMK(@me)\"/]\r\n																	</li>\r\n																</ul>\r\n															</div>\r\n														</li>\r\n														<li class=\"clearBoth\"></li>",0,635);
$z[0][4]['titlelen']="42";
$z[0][4]['row']="3";

?>