{dede:arclist titlelen='42' row='3'}
														<li class="content column-num1">
															<div class="newstitle">
																<ul>
																	<li class="title">
																		<h3><a href="http://www.mujiang.com/news_detail/newsId=13.html" title="[field:title/]-深圳展会消息" target="_self"> [field:title/]...</a></h3>
																	</li>
																	<li class="date">
																		<span></span>[field:pubdate function="GetDateMK(@me)"/]
																	</li>
																</ul>
															</div>
														</li>
														<li class="clearBoth"></li>{/dede:arclist}