<li class="first">
													<a href="http://www.mujiang.com/index.html" title="首页"> 首页</a>
												</li>
												<li>
													<a href="{dede:field name='typeurl'/}">{dede:field name='typename'/}</a>
												</li>
												<li>
													<a href="http://www.mujiang.com/news_list/columnsId=4.html" rel="summenu_FrontColumns_navigation01-1383536761574_4" title="新闻中心" class=""> 新闻中心</a>
												</li>
												<li>
													<a href="http://www.mujiang.com/products_list/columnsId=3.html" rel="summenu_FrontColumns_navigation01-1383536761574_3" title="大师作品" class=""> 大师作品</a>
												</li>
												<li>
													<a href="http://www.mujiang.com/mj_yxwl/columnsId=5.html" title="营销网络"> 营销网络</a>
												</li>
												<li>
													<a href="http://www.mujiang.com/job_list/columnsId=6.html" title="招贤纳士"> 招贤纳士</a>
												</li>
												<li>
													<a href="http://www.mujiang.com/members_fwzx/columnsId=7.html" rel="summenu_FrontColumns_navigation01-1383536761574_7" title="服务中心"> 服务中心</a>
												</li>
												<li class="last"></li>
											</ul>
										</div>
										<ul id="summenu_FrontColumns_navigation01-1383536761574_2" class="ddsubmenustyle" style="z-index: 2000; visibility: hidden;">{dede:channel type='son' noself='yes'}
											<li>
												<a href="[field:typelink/]">[field:typename/]</a>
											</li>{/dede:channel}