<?php
$z[0]=Array("arcurl","",142,157);
$z[1]=Array("title","",166,206);
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("litpic","",278,293);
$z[3]=Array("arcurl","",318,333);
$z[4]=Array("title","",345,385);
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("title","",394,434);
$z[5][4]['function']="html2text(@me)";
$z[6]=Array("title","",674,714);
$z[6][4]['function']="html2text(@me)";
$z[7]=Array("title","",897,937);
$z[7][4]['function']="html2text(@me)";

?>