<?php
$z[0]=Array("field","",28,56);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",121,150);
$z[1][4]['name']="typename";
$z[2]=Array("field","",153,182);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n											<li>\r\n												<a href=\"[field:typelink/]\"> [field:typename/]</a>\r\n											</li>\r\n										\r\n										</ul>",433,614);
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>