<?php
$z[0]=Array("litpic","",142,157);
$z[1]=Array("title","",166,206);
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("litpic","",278,293);
$z[3]=Array("litpic","",314,329);
$z[4]=Array("title","",337,377);
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("title","",386,426);
$z[5][4]['function']="html2text(@me)";
$z[6]=Array("title","",666,706);
$z[6][4]['function']="html2text(@me)";
$z[7]=Array("litpic","",822,837);
$z[8]=Array("title","",846,886);
$z[8][4]['function']="html2text(@me)";

?>