<li class="content column-num2">
																	<div class="pic-module">
																		<div class="pic">
																			<a href="[field:arcurl/]" title="[field:title function='html2text(@me)'/]" target="_self"> <img id="FrontProducts_list01-1384134850405_269" src="[field:litpic/]" onerror="this.src=&#39;/images/common/noimage.jpg&#39;" alt="[field:title function='html2text(@me)'/]" title="[field:title function='html2text(@me)'/]"> </a>
																		</div>
																	</div>
																	<div class="pro-module">
																		<ul class="basic">
																			<li class="code">
																				<h1><span>产品名称：</span><strong> [field:title function='html2text(@me)'/]</strong></h1>
																			</li>
																			<li class="detaillinks">
																				<a href="http://www.mujiang.com/products_detail/&productId=269.html" title="[field:title function='html2text(@me)'/]" target="_self">详细内容</a>
																			</li>
																		</ul>
																		<p class="buttonP"></p>
																	</div>
																</li>
				
																<li class="clearBoth"></li>