{dede:arclist titlelen='42' row='6'}
													<li class="content column-num1">
														<div class="newstitle">
															<ul>
																<li class="title">
																	<h3><a href="[field:arcurl/]" title="[field:title/]" target="_self">[field:title/]</a></h3>
																</li>
															</ul>
														</div>
													</li>
													<li class="clearBoth"></li>
													<li class="showLine"></li>{/dede:arclist}